### ISSUE TITLE
Undefined value of x

### ISSUE THREAD

**Issue by vickysharma0812** [Goddard-Fortran-Ecosystem/pFUnit_demos#10]
https://github.com/Goddard-Fortran-Ecosystem/pFUnit_demos/blob/eae49e1f7a0e2ba002f1c5dfbeceb3c51026b878/Basic/tests/test_failing.pf#L35

In about code what is the purpose of not defining the values of x?
It it intentionally done?

I encounter following error.

```bash
Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_UNDERFLOW_FLAG IEEE_DENORMAL
ERROR STOP *** Encountered 1 or more failures/errors during testing. ***

Error termination. Backtrace:
#0  0x7fc77e86ed21 in ???
#1  0x7fc77e86f869 in ???
#2  0x7fc77e870f97 in ???
#3  0x5589a46639d1 in ???
#4  0x5589a4674a1a in ???
#5  0x5589a458a809 in ???
#6  0x5589a458a84d in ???
#7  0x7fc77e5190b2 in ???
#8  0x5589a45874ed in ???
#9  0xffffffffffffffff in ???
```

Regards
Vikas

**Comment by tclune** [comment]
Ah - thanks.   I'm surprised this was not caught when I last tested these.    I suspect I refactored to avoid the need for local variables, but did not clean up.   I'll put in a change immediately.
